"area:app":
  - changed-files:
      - any-glob-to-any-file:
          - app/**
          - app/src/**

"area:ci":
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/actions/**

"area:infra":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - "! .github/workflows/**"

"release-notes":
  - changed-files:
      - any-glob-to-any-file: CHANGELOG.md

"area:gradle":
  - changed-files:
      - any-glob-to-any-file:
          - app/build.gradle
          - app/build.gradle.kts
          - build.gradle
          - build.gradle.kts
          - settings.gradle
          - settings.gradle.kts
          - gradle.properties
          - gradle/**