# Labeler configuration for automatic PR labeling based on changed files
# Each label maps to file patterns that trigger the label

'area: app':
  - app/**
  - '!app/build/**'
  - '!app/**/*.iml'

'area: data':
  - data/**

'area: domain':
  - domain/**

'area: ci':
  - .github/**
  - '!.github/labeler.yml'

'area: docs':
  - '*.md'
  - 'docs/**'
  - '.github/PULL_REQUEST_TEMPLATE/**'

'area: build':
  - 'build.gradle.kts'
  - 'settings.gradle.kts'
  - 'gradle/**'
  - 'gradlew'
  - 'gradlew.bat'
  - 'gradle.properties'

'type: android':
  - '**/AndroidManifest.xml'
  - '**/*.xml'
  - 'app/src/main/res/**'
  - 'app/proguard-rules.pro'

'type: kotlin':
  - '**/*.kt'
