app:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/**'

data:
  - changed-files:
      - any-glob-to-any-file:
          - 'data/**'

domain:
  - changed-files:
      - any-glob-to-any-file:
          - 'domain/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

gradle:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.gradle'
          - '**/*.gradle.kts'
