# Labeler configuration for automatic PR labeling based on changed files
# Format required for actions/labeler@v6

'area: app':
  - changed-files:
    - any-glob-to-any-file: 'app/**'

'area: data':
  - changed-files:
    - any-glob-to-any-file: 'data/**'

'area: domain':
  - changed-files:
    - any-glob-to-any-file: 'domain/**'

'area: ci':
  - changed-files:
    - any-glob-to-any-file: '.github/**'

'area: docs':
  - changed-files:
    - any-glob-to-any-file: '*.md'

'area: build':
  - changed-files:
    - any-glob-to-any-file: 'build.gradle.kts'
  - changed-files:
    - any-glob-to-any-file: 'settings.gradle.kts'
  - changed-files:
    - any-glob-to-any-file: 'gradle/**'

'type: android':
  - changed-files:
    - any-glob-to-any-file: '**/AndroidManifest.xml'

'type: kotlin':
  - changed-files:
    - any-glob-to-any-file: '**/*.kt'
